### ISSUE TITLE
Fork

### ISSUE THREAD

**Issue by Owlchemist** [jhjjgu0115/GloomyFurniture#23]
Hello - I am the author of [Gloomy Vanilla](https://steamcommunity.com/sharedfiles/filedetails/?id=1697864590) and I wanted to get a message over to the devs through quieter channels away from steam.

It is becoming apparent to me now that maintaining this mod is becoming a bit more work than I first realized. Gloomy Vanilla was just a personal mod I made and also a learning experience with patch operations for the first time. I also did not realize GloomyFurniture was as actively developed as it was at the time.

I'd like to know if you've any interest in taking over this mod in an official capacity as a variant to your own. Based on the subscription numbers, it seems to me that at least a tenth of the users have some interest in what its doing. If you have no interest in this, then I may alternatively ask if Gloomy Vanilla could just be a stand-alone mod (aka a fork) instead of a mod-mod, which would spare it from any problems when the main mod gets updated. Let me know what you think :)

**Comment by jhjjgu0115** [comment]
Hello, thank you for your interest in this mod. 
Our original intention was to separate it into the current tab (Old Style) to give user chance to use it with vanilla furniture.  So we chose a separate tab, not a texture change.

We don't want to create an stand-alone mod that includes this mod. 
But the way your patch works after the user subscribes to this mod is fine.
It's also okay to make your own new furniture mod by referring to our code and texture.
